name: visual-regression
on: [push]

jobs:
  save-screenshot:
    name: save screenshot
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true
      - run: bundle exec rspec --pattern spec/screen_shot/**/*_spec.rb
      - name: Upload screenshots of main
        uses: actions/upload-artifact@v3
        with:
          name: main-screen-shots
          path: tmp/capybara

  compare:
    name: compare screenshot
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - uses: actions/cache@v3
        id: node_module_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - run: echo '${{ toJSON(steps.node_modules_cache_id.outputs) }}'
      - if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: npm install
      - run: npm ls --depth=0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true
      - run: bundle exec rspec --pattern spec/screen_shot/**/*_spec.rb
      - name: Upload screenshots of main
        uses: actions/upload-artifact@v3
        with:
          name: main-screen-shots
          path: tmp/capybara
      - name: Download screenshots of main
        uses: actions/download-artifact@v3
        with:
          name: main-screen-shots
          path: tmp/main_screenshots
      - name: display files
        run: |
          ls -al tmp/capybara
          ls -al tmp/capybara
          ls -al tmp/main_screenshots
          ls -al node_modules/.bin
      - name: compare files
        run: |
          yarn reg-cli tmp/capybara  tmp/main_screenshots tmp/result
      - name: Upload diff screenshots
        uses: actions/upload-artifact@v3
        with:
          name: diff-screen-shots
          path: tmp/result
